fix(small): button play icon, bread crumbs, drop down list, scroll, r…
recruitment-process/recruitment-process-frontend pull request #50
Opened 2023-08-10 18:46 UTC by Pavelsmcom

…outing

2023-08-10 21:14 UTC, ds-sev requested changes
В целом всё ок.  Но, есть пара моментов, на которые стоит обратить внимание. *Если не было описания поведения этих сценариев от дизайнеров, считаю пока что можно проигнорировать.
1. Каждый новый выпадающий список открывается ЗА открытым ранее:
https://github.com/recruitment-process/recruitment-process-frontend/assets/99210830/343ef04f-5ae8-45df-a920-45b33aea16b2
2. Не понятно по цветам в выпадающем списке. Что должно быть фиолетовым, а что серым🤔:
![Снимок экрана 2023-08-10 в 23 22 20](https://github.com/recruitment-process/recruitment-process-frontend/assets/99210830/5de8f9b1-3b8d-4f01-a5a5-9b7f050aa82a)
3.Не хватает паддинга справа для секции. Слишком быстро "прилипает" к краю страницы:
https://github.com/recruitment-process/recruitment-process-frontend/assets/99210830/f8424fcf-0049-4208-80d1-c427ab828cd1
 Пока нет макета с адаптивом и указания минимальной рабочей ширины страницы, считаю, также можно пренебречь.
4. Срезается список кандидатов при высоте 785px и меньше:
https://github.com/recruitment-process/recruitment-process-frontend/assets/99210830/29485f7a-4d20-4633-9919-ce9b00533c03
Можно вылечить задав, например, минимальную высоту для списка, но, опять же есть ли в этом смысл, пока нет требования по минимальной рабочей высоте?..

2023-08-10 21:26 UTC, ds-sev approved these changes
В целом всё ок.  Но, есть пара моментов, на которые стоит обратить внимание. *Если не было описания поведения этих сценариев от дизайнеров, считаю пока что можно проигнорировать.
1. Каждый новый выпадающий список открывается ЗА открытым ранее:
https://github.com/recruitment-process/recruitment-process-frontend/assets/99210830/343ef04f-5ae8-45df-a920-45b33aea16b2
2. Не понятно по цвету текста в выпадающем списке. Что должно быть фиолетовым, а что серым🤔:
![Снимок экрана 2023-08-10 в 23 22 20](https://github.com/recruitment-process/recruitment-process-frontend/assets/99210830/5de8f9b1-3b8d-4f01-a5a5-9b7f050aa82a)
3. Не хватает паддинга справа для секции. Слишком быстро "прилипает" к краю страницы:
https://github.com/recruitment-process/recruitment-process-frontend/assets/99210830/f8424fcf-0049-4208-80d1-c427ab828cd1
 Пока нет макета с адаптивом и указания минимальной рабочей ширины страницы, считаю, также можно пренебречь.
4. Срезается список кандидатов при высоте 785px и меньше:
https://github.com/recruitment-process/recruitment-process-frontend/assets/99210830/29485f7a-4d20-4633-9919-ce9b00533c03
Можно вылечить задав, например, минимальную высоту для списка, но, опять же есть ли в этом смысл, пока нет требования по минимальной рабочей высоте?..

2023-08-14 11:52 UTC, Bjorn86 commented on src/utils/debounce.js
Как правило утилитарные функции не выносят в отдельный файл по названию функции, а складируют все в `utils.js`

2023-08-14 11:55 UTC, Bjorn86 commented
При обновлении страницы внутри вакансии слетает активный таб. Например, находимся в "Избранные", обновляем страницу, и оказываемся в "Активные"
https://www.vidline.com/share/V0YOHJN5D8/84f95b69ff0849517e38fa37cd3d9362

2023-08-14 11:58 UTC, Bjorn86 commented
А вот следующие даже не знаю, можно ли назвать багом, но по мне поведение не совсем логичное. При выборе вакансии и смене в ней таба, данный таб сохраняется как активный даже если выйдем на экран "Вакансии" и выберем другую вакансию.
https://www.vidline.com/share/V0G2HO1K2N/a6d0a459f7c213980be5cff28a6ed7cd

2023-08-22 06:53 UTC, ds-sev approved these changes
Привет. Есть несколько мелочей, на которые стоит обратить внимание:
1. Высота выпадающего списка больше на 4пх, чем в макете.
2. Нет ховера на табах навигации. В макете указан.
3. Контент при сужении страницы прилипает к правому краю. Хотя бы до минимально допустимой ширины 1330пх надо сделать красиво.
4. Вот этот компонент вынести бы в общие:
![Снимок экрана 2023-08-22 в 09 27 28](https://github.com/recruitment-process/recruitment-process-frontend/assets/99210830/7c5ebac5-3957-4270-9141-4c72d2d49f04)

2023-08-22 11:21 UTC, Bjorn86 commented
По визуалу поддерживаю замечания Димы. По п. 3, я бы не заморачивался с адаптивом, так как с ним нечего не понятно, но дал бы паддинга справа `32px`, что в принципе бы соответствовало макету

2023-08-22 11:58 UTC, Bjorn86 commented on src/components/CandidatesTable/CandidatesTable.jsx
> +  const handleSCrollPosition = useCallback(() => {
Можно не сейчас, но на будущее, вынести всё что касается скрола вынести в кастомный хук

2023-08-22 11:58 UTC, Bjorn86 commented on src/components/CandidatesTable/CandidatesTable.jsx
> +      // console.log('click', sortCandidates);
Коммент можно и удалить )

2023-08-22 11:58 UTC, Bjorn86 commented on src/components/UI/Input/Input.jsx
> +const Input = () => {
Насколько нужен компонент с учётом того, что ты его в итоге не используешь?

2023-08-24 07:28 UTC, ds-sev approved these changes
👌

2023-08-24 11:28 UTC, merged