feat(component vacancycard): vacancyCard component
recruitment-process/recruitment-process-frontend pull request #53
Opened 2023-08-11 10:07 UTC by dzhaneta

добавлен компонент VacancyCard, в VacanciesPage добавлена ссылка-карточка "Новая вакансия". Также добавлены несколько новых иконок и скоректированные временные входящие данные по вакансиям в папке temp.
пришлось решать конфликты в lock файлах package.json и yarn - но вроде я там все правильно покрутила.

2023-08-11 16:02 UTC, ds-sev reviewed
У меня в основном по косметике:
1. Немного не сходится позиционирование по ПиксПерф:
![Снимок экрана 2023-08-11 в 17 40 44](https://github.com/recruitment-process/recruitment-process-frontend/assets/99210830/17329ac7-bc10-415f-bc56-4a1d174f639e)
2. Некоторые элементы отличаются по размеру/цвету:
![Снимок экрана 2023-08-11 в 17 42 12](https://github.com/recruitment-process/recruitment-process-frontend/assets/99210830/a7797bb5-68f4-4262-8df5-62d6b3539fdf)
3. Не уверен, что это тут нужно:
![Снимок экрана 2023-08-11 в 17 45 01](https://github.com/recruitment-process/recruitment-process-frontend/assets/99210830/231d59a8-86ba-4605-8304-4ecf2cd46ae6)
5. Думаю, будет хорошо, если все кликабельные компоненты, которые присутствуют, но пока не имеют функционала имели какую-то заглушку. Напр. выводили что-то в консоль или просто хотя бы нажимались без действия:
![Снимок экрана 2023-08-11 в 17 52 22](https://github.com/recruitment-process/recruitment-process-frontend/assets/99210830/e9a660c0-ebfe-42a5-95ae-7a5f851ef902)
6. Нет ховера у кликабельных элементов
7. Что-то не то с иконкой "+" 🙃 Возможно лучше использовать готовую цветную из макета.

2023-08-12 10:00 UTC, Pavelsmcom commented
> У меня в основном по косметике:
> 
> 1. Немного не сходится позиционирование по ПиксПерф:
>    ![Снимок экрана 2023-08-11 в 17 40 44](https://user-images.githubusercontent.com/99210830/260041471-17329ac7-bc10-415f-bc56-4a1d174f639e.png)
> 2. Некоторые элементы отличаются по размеру/цвету:
>    ![Снимок экрана 2023-08-11 в 17 42 12](https://user-images.githubusercontent.com/99210830/260041802-a7797bb5-68f4-4262-8df5-62d6b3539fdf.png)
> 3. Не уверен, что это тут нужно:
>    ![Снимок экрана 2023-08-11 в 17 45 01](https://user-images.githubusercontent.com/99210830/260042325-231d59a8-86ba-4605-8304-4ecf2cd46ae6.png)
> 4. Думаю, будет хорошо, если все кликабельные компоненты, которые присутствуют, но пока не имеют функционала имели какую-то заглушку. Напр. выводили что-то в консоль или просто хотя бы нажимались без действия:
>    ![Снимок экрана 2023-08-11 в 17 52 22](https://user-images.githubusercontent.com/99210830/260045741-e9a660c0-ebfe-42a5-95ae-7a5f851ef902.png)
> 5. Нет ховера у кликабельных элементов
> 6. Что-то не то с иконкой "+" 🙃 Возможно лучше использовать готовую цветную из макета.

2023-08-12 10:02 UTC, Pavelsmcom commented
Привет! Спасибо за проделанную работу, всё хорошо, но есть несколько замечаний:

1. Присоединяюсь к замечаниям Димы по pixelPerfect и БЭМ
2. Заменить заголовок с h6 на h3 или h4
3. Уже сейчас сделать, чтобы ссылкой на вакансию был не весь элемент. Чтобы клик по "..." не вёл на переход на вакансию, ссылка на календарь не вела на переход вакансию и т.д. (Надеюсь понятно объяснил)
4. Последнюю пустую карточку (Новая вакансия) я бы тоже переместил в vacanciesList. (После того, как мы сделали Map в конец массива добавлял бы разметку для пустой карточки)
5. Может быть исправить структуру: сейчас у нас идёт <div> в который входят ссылки <a>: Может быть карточку сделать изначально не как ссылку а как div или article, а внутри уже поместить ссылку? Или если оставить ссылки, то рассматривать это как навигацию и тогда ссылки поместить в nav?
![Screenshot_1](https://github.com/recruitment-process/recruitment-process-frontend/assets/71379163/d559c6d6-dc67-4f75-8447-7267e0832903)

2023-08-12 10:05 UTC, Pavelsmcom requested changes

2023-08-12 10:05 UTC, Pavelsmcom commented on src/components/VacancyCard/VacancyCard.jsx
> +        <h6 className="card__title">{title}</h6>
Я бы заменил заголовок с h6 на h3 или h4

2023-08-12 11:28 UTC, ds-sev commented on src/components/VacancyCard/VacancyCard.scss
> +  &__tag {
вот этот элемент лучше вынести в отдельный UI-компонент. Точно будет использоваться в профиле кандидата и, возможно позже, где-то еще.

2023-08-14 12:35 UTC, Bjorn86 commented on src/components/VacanciesPage/VacanciesPage.jsx
> +            style={{ textDecoration: 'none' }}
Инлайн стиль, а мы их не используем. Нужно добавить класс и стилизовать через него

2023-08-14 12:35 UTC, Bjorn86 commented on package.json
> +    "esbuild": "0.18.18",
Этот пакет и его производные в текущей версии `develop` уже нет. Удали его пожалуйста )

2023-08-14 12:35 UTC, Bjorn86 commented on src/components/VacanciesPage/VacanciesPage.jsx
>              to="vacancy"
С учётом того, что у нас уже есть моковые данные и то что Паша перевёл вакансию на динамический роутинг, лучше сразу сделать формирование ссылки по этим данным

2023-08-14 12:35 UTC, Bjorn86 commented on src/components/VacanciesPage/VacanciesPage.jsx
> +          style={{ textDecoration: 'none' }}
Инлайн стиль, а мы их не используем. Нужно добавить класс и стилизовать через него

2023-08-15 13:27 UTC, dzhaneta commented on src/components/VacancyCard/VacancyCard.jsx
> +      <div className="card__wrapper_1">
изменено на card__brief

2023-08-15 13:27 UTC, dzhaneta commented on src/components/VacancyCard/VacancyCard.jsx
> +      <div className="card__wrapper_2">
изменено на card__content

2023-08-15 13:38 UTC, dzhaneta commented on src/components/VacancyCard/VacancyCard.jsx
> +        <h6 className="card__title">{title}</h6>
изменено на h4

2023-08-15 14:18 UTC, dzhaneta commented on package.json
> +    "esbuild": "0.18.18",
удалено

2023-08-15 14:31 UTC, dzhaneta commented on src/components/VacancyCard/VacancyCard.jsx
> +              `}
применила

2023-08-16 13:47 UTC, dzhaneta commented on src/components/VacancyCard/VacancyCard.scss
> +  &__tag {
done

2023-08-21 19:39 UTC, dzhaneta commented
> У меня в основном по косметике:
> 
> 1. Немного не сходится позиционирование по ПиксПерф:
>    ![Снимок экрана 2023-08-11 в 17 40 44](https://user-images.githubusercontent.com/99210830/260041471-17329ac7-bc10-415f-bc56-4a1d174f639e.png)
> 2. Некоторые элементы отличаются по размеру/цвету:
>    ![Снимок экрана 2023-08-11 в 17 42 12](https://user-images.githubusercontent.com/99210830/260041802-a7797bb5-68f4-4262-8df5-62d6b3539fdf.png)
> 3. Не уверен, что это тут нужно:
>    ![Снимок экрана 2023-08-11 в 17 45 01](https://user-images.githubusercontent.com/99210830/260042325-231d59a8-86ba-4605-8304-4ecf2cd46ae6.png)
> 4. Думаю, будет хорошо, если все кликабельные компоненты, которые присутствуют, но пока не имеют функционала имели какую-то заглушку. Напр. выводили что-то в консоль или просто хотя бы нажимались без действия:
>    ![Снимок экрана 2023-08-11 в 17 52 22](https://user-images.githubusercontent.com/99210830/260045741-e9a660c0-ebfe-42a5-95ae-7a5f851ef902.png)
> 5. Нет ховера у кликабельных элементов
> 6. Что-то не то с иконкой "+" 🙃 Возможно лучше использовать готовую цветную из макета.

правки внесены в коммите [fade38b](https://github.com/recruitment-process/recruitment-process-frontend/pull/53/commits/fade38b2999f7a6af581de3df89dda6804b989d7)

2023-08-21 22:01 UTC, dzhaneta commented
> fc0c1bf

все правки внесены при коммите [fc0c1bf](https://github.com/recruitment-process/recruitment-process-frontend/pull/53/commits/fc0c1bf6982dc21d17cc86e40ac8bb2d12e1f4ea)

2023-08-21 22:02 UTC, dzhaneta commented
> Привет! Спасибо за проделанную работу, всё хорошо, но есть несколько замечаний:
> 
> 1. Присоединяюсь к замечаниям Димы по pixelPerfect и БЭМ
> 2. Заменить заголовок с h6 на h3 или h4
> 3. Уже сейчас сделать, чтобы ссылкой на вакансию был не весь элемент. Чтобы клик по "..." не вёл на переход на вакансию, ссылка на календарь не вела на переход вакансию и т.д. (Надеюсь понятно объяснил)
> 4. Последнюю пустую карточку (Новая вакансия) я бы тоже переместил в vacanciesList. (После того, как мы сделали Map в конец массива добавлял бы разметку для пустой карточки)
> 5. Может быть исправить структуру: сейчас у нас идёт  в который входят ссылки : Может быть карточку сделать изначально не как ссылку а как div или article, а внутри уже поместить ссылку? Или если оставить ссылки, то рассматривать это как навигацию и тогда ссылки поместить в nav?
>    ![Screenshot_1](https://user-images.githubusercontent.com/71379163/260219826-d559c6d6-dc67-4f75-8447-7267e0832903.png)

все правки внесены при коммите [fc0c1bf](https://github.com/recruitment-process/recruitment-process-frontend/pull/53/commits/fc0c1bf6982dc21d17cc86e40ac8bb2d12e1f4ea)

2023-08-21 22:02 UTC, dzhaneta commented on src/components/VacanciesPage/VacanciesPage.jsx
> +          style={{ textDecoration: 'none' }}
исправлено в коммите [fc0c1bf](https://github.com/recruitment-process/recruitment-process-frontend/pull/53/commits/fc0c1bf6982dc21d17cc86e40ac8bb2d12e1f4ea)

2023-08-21 22:02 UTC, dzhaneta commented on src/components/VacanciesPage/VacanciesPage.jsx
> +            style={{ textDecoration: 'none' }}
исправлено в коммите [fc0c1bf](https://github.com/recruitment-process/recruitment-process-frontend/pull/53/commits/fc0c1bf6982dc21d17cc86e40ac8bb2d12e1f4ea)

2023-08-21 22:03 UTC, dzhaneta commented on src/components/VacanciesPage/VacanciesPage.jsx
>              to="vacancy"
не поняла твой комментарий, напиши мне в личку в тг плз

2023-08-22 07:29 UTC, ds-sev approved these changes
Я нашел пару моментов:
1. <img width="419" alt="Снимок экрана 2023-08-22 в 10 11 01" src="https://github.com/recruitment-process/recruitment-process-frontend/assets/99210830/f609b25f-e06f-4b5d-8fa4-165b92b40739">
Я так понимаю, имеется ввиду что карточки скроллятся отдельно от бокового меню и хэдера (как было со списком кандидатов в "Вакансии") Лучше уточнить у дизайнеров.
2. Если табов становится больше, дата и кнопка share уходят вниз:
![Снимок экрана 2023-08-22 в 10 16 07](https://github.com/recruitment-process/recruitment-process-frontend/assets/99210830/f6b8eb92-e837-47d0-be71-dc2eb08e516e) Тут тоже к дизайнерам.

В остальном всё отлично. В целом, если у других нет критичных замечаний, мои можно запомнить и исправить при дальнейшей работе, чтоб не затягивать процесс.

2023-08-22 21:00 UTC, ds-sev commented on src/components/VacanciesPage/VacanciesPage.scss
> +    overflow-x: hidden;
Теперь обрезаются тени карточек:
![Снимок экрана 2023-08-22 в 23 45 17](https://github.com/recruitment-process/recruitment-process-frontend/assets/99210830/7b81768c-87b1-4196-93e3-df040b3f4919)

2023-08-23 03:59 UTC, Pavelsmcom approved these changes

2023-08-23 18:41 UTC, merged

2023-08-23 18:43 UTC, dzhaneta commented
как договорились, смерджила текущий вид для ревью
параллельно решаю проблему с прокруткой и пропадающими тенями карточек